import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import type { Order, Store } from '@delivery/contracts';
import { api, session } from './api/client';

type Data = { profile: Record<string, string>; addresses: { address: string; detail?: string; isDefault?: boolean }[]; payments: any[]; notifications: Record<string, boolean>; app: Record<string, any> };
const blank: Data = { profile: {}, addresses: [], payments: [], notifications: {}, app: { language: 'ko' } };
const Block = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="order"><h2>{title}</h2>{children}</section>;
export function MyPage() { const [data, setData] = useState<Data>(blank), [favorites, setFavorites] = useState<Store[]>([]), [orders, setOrders] = useState<Order[]>([]), [road, setRoad] = useState(''), [detail, setDetail] = useState(''), [note, setNote] = useState(''); useEffect(() => { if (!session.token) return location.assign('/login'); Promise.all([api.userSettings(), api.favorites(), api.orders()]).then(([a,b,c]) => { setData({ ...blank, ...a.data, profile: a.data.profile ?? {}, addresses: a.data.addresses ?? [] }); setFavorites(b.data); setOrders(c.data); }).catch(e => setNote(e.message)); }, []); const save = async (next = data) => { const r = await api.saveUserSettings(next); setData(r.data); setNote('저장되었습니다.'); }; const addAddress = async () => { if (!road.trim()) return setNote('도로명 주소를 입력해 주세요.'); const addresses = [...data.addresses.map(x => ({ ...x, isDefault: false })), { address: road.trim(), detail: detail.trim(), isDefault: true }]; await save({ ...data, addresses }); setRoad(''); setDetail(''); }; const removeAddress = async (index: number) => { const addresses = data.addresses.filter((_, i) => i !== index); await save({ ...data, addresses }); }; return <main><h1>마이페이지</h1>{note && <p className="muted">{note}</p>}<Block title="내 프로필"><input placeholder="이름" value={data.profile.name ?? ''} onChange={e => setData({ ...data, profile: { ...data.profile, name: e.target.value } })} /><input placeholder="휴대폰 번호" value={data.profile.phone ?? ''} onChange={e => setData({ ...data, profile: { ...data.profile, phone: e.target.value } })} /><button onClick={() => save()}>프로필 저장</button></Block><Block title="배송지 관리"><p className="muted">기본 배송지는 주문 시 자동으로 사용됩니다.</p><input placeholder="도로명 주소 (예: 대신로 73번길 50)" value={road} onChange={e => setRoad(e.target.value)} /><input placeholder="상세주소 (예: 204동 104호)" value={detail} onChange={e => setDetail(e.target.value)} /><button onClick={addAddress}>이 배송지를 기본으로 저장</button>{data.addresses.map((a, i) => <div className="cart-item" key={i}><span>{a.isDefault ? '기본 배송지 · ' : ''}{a.address} {a.detail}</span><button onClick={() => removeAddress(i)}>삭제</button></div>)}</Block><Block title="즐겨찾기">{favorites.map(s => <div className="cart-item" key={s.id}><Link to={`/stores/${s.id}`}>{s.name} · ❤️ {s.favoriteCount}</Link><button onClick={async () => { await api.removeFavorite(s.id); setFavorites(favorites.filter(x => x.id !== s.id)); }}>삭제</button></div>)}</Block><Block title="주문내역">{orders.map(o => { const x = o as Order & { storeName?: string; _id?: string }; return <article className="order" key={x.id ?? x._id}><strong>{x.store?.name ?? x.storeName ?? '가게'} · {x.status}</strong><p>{x.totalAmount.toLocaleString()}원</p></article>; })}</Block><Block title="계정"><button onClick={() => { session.clear(); location.assign('/'); }}>로그아웃</button><button onClick={() => confirm('정말 회원탈퇴하시겠습니까?') && (session.clear(), location.assign('/'))}>회원탈퇴</button></Block></main> }
